---
- hosts: "{{hosts}}"
  become: true 
  gather_facts: False
 
  tasks:

  - name: Start NTP service if not running 
    service: name=ntpd state=started 
  
  - name:  Check ntp sync status
    shell: timedatectl status
    register: result
    failed_when: '"NTP synchronized: no" in result.stdout'
    ignore_errors: true 

  - name: Restart NTP service if no sync detected
    service: name=ntpd state=restarted 
    when: '"NTP synchronized: no" in result.stdout'

